rateControl: &rate
  type: fixed-rate
  opts:
    tps: 500

test:
  name: smallbank
  description: Initialize accounts
  workers:
    number: 5
  rounds:
    - label: init
      txNumber: 2000
      rateControl: *rate
      workload:
        module: benchmarks/scenario/smallbank/customWorkLoad.js
        arguments:
          contractId: smallbank
          contractVersion: '1.0'
          txFilePath: ../../data/smallbank_workload/init_accounts.json
